prefix = "."
stop-words = "stopwords.txt"

dataset = "train"
corpus = "line.toml"
index = "idx"

query-judgements = "train/qrels.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[query-runner]
query-id-start = 1